spring:
  application:
    name: ebilling

  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:15432}/${DB_NAME:ebilling}
    username: ${DB_USER:ebilling}
    password: ${DB_PASSWORD:ebilling}
    hikari:
      maximum-pool-size: 10

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: false
    locations: classpath:db/migration,classpath:db/callbacks

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:${KAFKA_HOST_PORT:9094}}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
    consumer:
      group-id: ebilling-local
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:${REDIS_HOST_PORT:6379}}

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:${MAILHOG_SMTP_PORT:2525}}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized

# -------- Docker profile (inside containers) --------
---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:ebilling}
    username: ${DB_USER:ebilling}
    password: ${DB_PASSWORD:ebilling}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

  mail:
    host: ${MAIL_HOST:mailhog}
    port: ${MAIL_PORT:1025}

management:
  endpoint:
    health:
      show-details: always
